#!/home/shino/.anyenv/envs/pyenv/shims/python
import sys
from collections import Counter

n = int(input())
ans = None

for i in range(1, n//2):
    for j in range(1, n-i):
        xy_gap = abs(i - j)
        rest = n - (i * j)
        tmp = rest + xy_gap
        if ans == None or tmp < ans:
            ans = tmp

print(ans)
